
  <p><?= $animationSent ?? '' ?></p>
  <p><?= $empty ?? '' ?></p>
  <form method='POST' enctype = "multipart/form-data" > 
    <fieldset>
        <legend>Enter your animation here</legend>
        <div class="group">
            <label for="name">Name</label>
            <input type="text" name="name" autocomplete="off" class="inputMargin"/>            
        </div>
        <div class="group">
            <label for="category">Category</label>
            <input type="text" name="category" autocomplete="off" class="inputMargin"/>            
        </div>
        <div class="Form">
            <label for="gif">Gif</label>
            <input type="text" name="gif" autocomplete="off" class="inputMargin"/>            
        </div>
        <div class="Form">
            <label for="html_content">HTML Code</label>
            <input type="text" name="html_content" class="inputMargin"/>            
        </div>
         <div class="Form">
            <label for="css_content">CSS Code</label>
            <input type="text" name="css_content" class="inputMargin"/>            
        </div>
        <input type="submit" name="submit" value="submit"/>
    </fieldset>
</form>