
<link rel="stylesheet" href="./Assets/Css/home.css">
<!--I want theses links to be different from the others pages-->
    <div class= header>
            <a href="./contact">Contact</a>
           
    </div>
  
               <div class= Home_Block>
                     <p class= "Animated_Title">Welcome to your animation library
                     </p>
                      <button class= Explore
                        type="button"><a href="./main?SearchBar=Recents">EXPLORE</a></button>
                </div> 
              
               <div class= Main_Block>
                    <div class="wave"></div>
              </div>
              
                  
